"""empty message

Revision ID: 07794606675b
Revises: 
Create Date: 2024-02-24 19:55:48.807745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07794606675b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_name', sa.String(length=50), nullable=False),
    sa.Column('pet_age', sa.Integer(), nullable=False),
    sa.Column('pet_type', sa.String(length=50), nullable=False),
    sa.Column('pet_weight', sa.Float(), nullable=False),
    sa.Column('pet_size', sa.String(length=20), nullable=False),
    sa.Column('pet_temper', sa.String(length=50), nullable=False),
    sa.Column('pet_guardian_id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_guardian_id'], ['user_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_pet_guardian_id'), ['pet_guardian_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_register_date'), ['register_date'], unique=False)

    op.create_table('pet_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_guardian_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_guardian_id'], ['user_client.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_schedules_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_schedules_id'))

    op.drop_table('pet_schedules')
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_register_date'))
        batch_op.drop_index(batch_op.f('ix_pet_pet_guardian_id'))
        batch_op.drop_index(batch_op.f('ix_pet_id'))

    op.drop_table('pet')
    # ### end Alembic commands ###
