"""empty message

Revision ID: 2bd301daa747
Revises: 
Create Date: 2024-02-28 19:28:40.981157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd301daa747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_client_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_client_register_date'), ['register_date'], unique=False)

    op.create_table('pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('pet_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('temper', sa.String(length=50), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['user_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_guardian_id'), ['guardian_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_register_date'), ['register_date'], unique=False)

    op.create_table('pet_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('schedules', sa.DateTime(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['user_client.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_schedules_schedules'), ['schedules'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_schedules_schedules'))
        batch_op.drop_index(batch_op.f('ix_pet_schedules_id'))

    op.drop_table('pet_schedules')
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_register_date'))
        batch_op.drop_index(batch_op.f('ix_pet_id'))
        batch_op.drop_index(batch_op.f('ix_pet_guardian_id'))

    op.drop_table('pet')
    with op.batch_alter_table('user_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_client_register_date'))
        batch_op.drop_index(batch_op.f('ix_user_client_id'))

    op.drop_table('user_client')
    # ### end Alembic commands ###
