"""empty message

Revision ID: 36fc80cefb76
Revises: f0486aa1dc28
Create Date: 2024-03-02 16:48:01.663609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fc80cefb76'
down_revision = 'f0486aa1dc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_pet_comments_guardia_id')
        batch_op.create_index(batch_op.f('ix_pet_comments_guardian_id'), ['guardian_id'], unique=False)
        batch_op.drop_constraint('pet_comments_guardia_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_client', ['guardian_id'], ['id'])
        batch_op.drop_column('guardia_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardia_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pet_comments_guardia_id_fkey', 'user_client', ['guardia_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_pet_comments_guardian_id'))
        batch_op.create_index('ix_pet_comments_guardia_id', ['guardia_id'], unique=False)
        batch_op.drop_column('guardian_id')

    # ### end Alembic commands ###
