"""empty message

Revision ID: 6920659f9d90
Revises: 09bf90ec4741
Create Date: 2024-03-06 20:32:09.730305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6920659f9d90'
down_revision = '09bf90ec4741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('office', sa.String(length=50), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_register_date'), ['register_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_register_date'))
        batch_op.drop_index(batch_op.f('ix_employee_id'))

    op.drop_table('employee')
    # ### end Alembic commands ###
