"""empty message

Revision ID: 6af3ca33e9fe
Revises: 07794606675b
Create Date: 2024-02-24 20:45:47.390010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af3ca33e9fe'
down_revision = '07794606675b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('temper', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('guardian_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_pet_pet_guardian_id')
        batch_op.create_index(batch_op.f('ix_pet_guardian_id'), ['guardian_id'], unique=False)
        batch_op.drop_constraint('pet_pet_guardian_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_client', ['guardian_id'], ['id'])
        batch_op.drop_column('pet_weight')
        batch_op.drop_column('pet_name')
        batch_op.drop_column('pet_temper')
        batch_op.drop_column('pet_guardian_id')
        batch_op.drop_column('pet_size')
        batch_op.drop_column('pet_age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pet_size', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pet_guardian_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pet_temper', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pet_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pet_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pet_pet_guardian_id_fkey', 'user_client', ['pet_guardian_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_pet_guardian_id'))
        batch_op.create_index('ix_pet_pet_guardian_id', ['pet_guardian_id'], unique=False)
        batch_op.drop_column('guardian_id')
        batch_op.drop_column('temper')
        batch_op.drop_column('size')
        batch_op.drop_column('weight')
        batch_op.drop_column('age')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
