"""empty message

Revision ID: a0b7c60f773d
Revises: eec6b881034b
Create Date: 2024-03-20 18:56:33.099161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b7c60f773d'
down_revision = 'eec6b881034b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_schedules', schema=None) as batch_op:
        # Adicionando a nova coluna
        op.add_column('pet_schedules', sa.Column('status', sa.String(length=20), default='Ativo'))
        # Atualizando todas as linhas existentes para garantir que não aja nulos
        op.execute('UPDATE pet_schedules SET status = \'Ativo\' WHERE status IS NULL')
        # Adicionando restrição NOT NULL
        op.alter_column('pet_schedules', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_schedules', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
