"""empty message

Revision ID: fa01d7e80553
Revises: 6af3ca33e9fe
Create Date: 2024-02-25 15:51:27.092242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa01d7e80553'
down_revision = '6af3ca33e9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('schedules', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_pet_schedules_schedules'), ['schedules'], unique=False)
        batch_op.drop_constraint('pet_schedules_pet_guardian_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_client', ['guardian_id'], ['id'])
        batch_op.drop_column('pet_guardian_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_guardian_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pet_schedules_pet_guardian_id_fkey', 'user_client', ['pet_guardian_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_pet_schedules_schedules'))
        batch_op.drop_column('schedules')
        batch_op.drop_column('guardian_id')

    # ### end Alembic commands ###
